config/routes.rb
Rails.application.routes.draw do
  resources :student_subjects
  resources :subjects
  resources :students
  resources :schools
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :school
  has_many :student_subjects, foreign_key: :student_id, dependent: :destroy
  has_many :subjects, through: :student_subjects

	validates :cedula, 
			presence: {:message  => "Introduzca la cedula del estudiante"},
			format: {with: /\A[A-Za-z0-9\s]+\z/, :message  => "Caracteres invalidos"},
 			numericality: { :message  => "No es un numero valido"},
 			uniqueness: { scope: :cedula, :message => "Cedula ya existe"}

 	validates :nombre,
            presence: { message: "Introduzca el nombre del estudiante" },
			format: {with: /\A([A-Za-z0-9ñÑ\-\.\ ]+)\z/, message: "Caracteres invalidos"}
 	
 	validates :apellido,
            presence: { message: "Introduzca el apellido del estudiante" },
			format: {with: /\A([A-Za-z0-9ñÑ\-\.\ ]+)\z/, message: "Caracteres invalidos"}

	validates :fecha_nac,
            presence: { message: "Introduzca la fecha de nacimiento del estudiante"}

    validates :genero,
            presence: { message: "Introduzca el genero del estudiante"}	

 	validates :school_id,
            presence: { message: "Introduzca el colegio del estudiante"}	           				

  #para los labels de simple_form
  def to_label
  	"#{self.cedula} - #{self.nombre} #{self.apellido}"
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @materias=StudentSubject.where(:student_id => @student.id)
    @promedio = @materias.average(:nota)
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:cedula, :nombre, :apellido, :fecha_nac, :genero, :school_id)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= simple_form_for(student) do |f| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label>Cedula</label>
    <%= f.text_field :cedula %>
  </div>

  <div class="field">
    <label>Nombre</label>
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <label>Apellido</label>
    <%= f.text_field :apellido %>
  </div>

  <div class="field">
    <%= f.label :fecha_nac %>
    <%= f.date_select :fecha_nac %>
  </div>

  <div class="field">
    <label>Genero</label>
    <%= f.input :genero, :collection => ['M','F'], :include_blank => "Seleccionar" %>
  </div>

  <div class="field">
  <label>Colegio</label>
    <%= f.association :school,label: false, label_method: :nombre, value_method: :id, :include_blank => "Seleccionar" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<div class="row">
   <div class="col-lg-12">
      <h1 class="page-header">Editar Estudiantes</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>


<div class="row">
   <div class="col-lg-12">
      <h1 class="page-header">Estudiantes</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>

              <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                <thead>
                  <tr class="text-align center">
                    <th><center>Cedula</center></th>
                    <th><center>Nombre</center></th>
                    <th><center>Apellido</center></th>
                    <th><center>Fecha Nacimiento</center></th>
                    <th><center>Genero</center></th>
                    <th><center>Colegio</center></th>
                    <th colspan="3"><center>Acción</center></th>
                  </tr>
                </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.cedula %></td>
        <td><%= student.nombre %></td>
        <td><%= student.apellido %></td>
        <td><%= student.fecha_nac %></td>
        <td><%= student.genero %></td>
        <!--Accedo al atributo nombre de la escuela del estudiante-->
        <td><%= student.school.nombre %></td>
        <td><%= link_to student do%>
                            <center><i class="fa fa-eye fa-md"></i></center>
                          <%end%>
                      </td>
                      <td><%= link_to edit_student_path(student) do%>
                           <center><i class="fa fa-pencil fa-md"></i></center>
                          <%end%>
                      </td>
                      <td><%= link_to student, method: :delete, data: { confirm: 'Are you sure?' }  do%>
                            <center><i class="fa fa-trash fa-md"></i></center>
                          <%end%>
                      </td>
                    </tr>
                  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<div class="row">
   <div class="col-lg-12">
      <h1 class="page-header">Agregar Estudiante</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>


<div class="row">
   <div class="col-lg-12">
      <h1 class="page-header">Estudiantes</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>
<p>
  <strong>Cedula: </strong>student.cedula </p>
<p>  <%= @student.cedula %>
</p>

<p>
  <strong>Nombre: </strong> student.nombre </p>
<p>  <%= @student.nombre %>
</p>

<p>
  <strong>Apellido: </strong> student.apellido </p>
<p>  <%= @student.apellido %>
</p>

<p>
  <strong>Fecha Nacimiento: </strong> student.fecha_nac </p>
<p>  <%= @student.fecha_nac %>
</p>

<p>
  <strong>Genero: </strong> student.genero </p>
<p>  <%= @student.genero %>
</p>

<p>
  <strong>Nombre del colegio: </strong> student.school.nombre </p>
  <!--Accedo al atributo nombre de la escuela del estudiante-->
 <p> <%= @student.school.nombre %>
</p>
<p>
<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>
</p>

<p>
<div class="row">
   <div class="col-lg-12">
      <h1 class="page-header">Materias</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>
<p><strong>Para la tabla: </strong>@materias=StudentSubject.where(:student_id => @student.id)</p>
    
<p>
  <strong>Promedio global:</strong> @promedio = @materias.average(:nota) </p>
  <!--Accedo al atributo nombre de la escuela del estudiante-->
<p>  <%= @promedio %>
</p>
</p>
              <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                <thead>
                  <tr class="text-align center">
                    <th><center>Nombre</center></th>
                    <th><center>Fecha Inscripcion</center></th>
                    <th><center>Nota</center></th>
                  </tr>
                </thead>

  <tbody>
    <% @materias.each do |mat| %>
      <tr>
        <td><%= mat.subject.nombre %></td>
        <td><%= mat.created_at %></td>
        <td><%= mat.nota %></td>
      </tr>
    <%end%>
  </tbody>
</table>