config/routes.rb
Rails.application.routes.draw do
  resources :student_subjects
  resources :subjects
  resources :students
  resources :schools
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :student_subjects, foreign_key: :subject_id, dependent: :destroy
  has_many :students, through: :student_subjects

  validates :nombre,
            presence: { message: "Introduzca el nombre de la materia" },
			format: {with: /\A([A-Za-z0-9ñÑ\-\.\ ]+)\z/, message: "Caracteres invalidos"}
 	
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
    @estudiantes=StudentSubject.where(:subject_id => @subject.id)
    @promedio=@estudiantes.average(:nota)
    @total_estudiantes= @estudiantes.count
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:nombre)
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_for(subject) do |f| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<div class="row">
   <div class="col-lg-12">
      <h1 class="page-header">Editar Materia</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>
<%= render 'form', subject: @subject %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
   <div class="col-lg-12">
      <h1 class="page-header">Materias</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>
              <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                <thead>
                  <tr class="text-align center">
                    <th><center>Nombre</center></th>
                    <th colspan="3"><center>Acción</center></th>
                  </tr>
                </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.nombre %></td>
        <td><%= link_to subject do%>
                            <center><i class="fa fa-eye fa-md"></i></center>
                          <%end%>
                      </td>
                      <td><%= link_to edit_subject_path(subject) do%>
                           <center><i class="fa fa-pencil fa-md"></i></center>
                          <%end%>
                      </td>
                      <td><%= link_to subject, method: :delete, data: { confirm: 'Are you sure?' }  do%>
                            <center><i class="fa fa-trash fa-md"></i></center>
                          <%end%>
                      </td>
                    </tr>
                  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject', new_subject_path %>

app/views/subjects/new.html.erb
<div class="row">
   <div class="col-lg-12">
      <h1 class="page-header">Nueva Materia</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>
<%= render 'form', subject: @subject %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
   <div class="col-lg-12">
      <h1 class="page-header">Materias</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>

<p>
  <strong>Nombre:</strong> @subject.nombre </p>
<p>  <%= @subject.nombre %>
</p>
<p>
<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>
</p>
<div class="row">
   <div class="col-lg-12">
      <h1 class="page-header">Estudiantes</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>
<p>
  <strong>Para la tabla :</strong> @estudiantes=StudentSubject.where(:subject_id => @subject.id)</p>
<p>  <%= @promedio %>
</p>
<p>
  <strong>Total estudiantes:</strong> @estudiantes.count</p>
<p>  <%= @total_estudiantes %>
</p>
<p>
  <strong>Promedio global:</strong> @estudiantes.average(:nota)</p>
<p>  <%= @promedio %>
</p>
<table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                <thead>
                  <tr class="text-align center">
                  <th><center>Colegio</center></th>
                    <th><center>Cedula</center></th>
                    <th><center>Nombre</center></th>
                    <th><center>Apellido</center></th>
                    <th><center>Fecha Nacimiento</center></th>
                    <th><center>Genero</center></th>
                    <th><center>Nota</center></th>
                  </tr>
                </thead>
  <tbody>
    <% @estudiantes.each do |estudiante| %>
      <tr>
      	<td><%= estudiante.student.school.nombre %></td>
        <td><%= estudiante.student.cedula %></td>
        <td><%= estudiante.student.nombre %></td>
        <td><%= estudiante.student.apellido %></td>
        <td><%= estudiante.student.fecha_nac %></td>
        <td><%= estudiante.student.genero %></td>
        <td><%= estudiante.nota %></td>
        </tr> 
        <%end%>       
  </tbody>
</table>