config/routes.rb
Rails.application.routes.draw do
  resources :student_subjects
  resources :subjects
  resources :students
  resources :schools
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/school.rb
class School < ApplicationRecord
	has_many :students

	validates :nombre,
            presence: { message: "Introduzca el nombre del colegio" },
			format: {with: /\A([A-Za-z0-9ñÑ\-\.\ ]+)\z/, message: "Caracteres invalidos"}
 	
 	validates :direccion,
            presence: { message: "Introduzca la direccion del colegio" },
			format: {with: /\A([A-Za-z0-9ñÑ\-\.\ ]+)\z/, message: "Caracteres invalidos"}
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
    #Obteniendo los estudiantes del colegio
    @estudiantes=Student.where(:school_id => @school.id)
    #El numero de estudiantes en el colegio:
    @num_total= @estudiantes.count
    #Numero de estudiantes genero masculino:
    @num_total_m= @estudiantes.where(:genero => "M").count
    #Las materias impartidas en el colegio:
    @id_materias=StudentSubject.select(:subject_id).joins(:student).where(
      :students => {:school_id => @school.id})
    @materias_impartidas=Subject.where(:id => @id_materias)
    #Promedio de esas materias (la linea de codigo esta en la vista)
    #StudentSubject.where(:subject_id => materia.id).average(:nota)
  
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:nombre, :direccion)
    end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= form_for(school) do |f| %>
  <% if school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :direccion %>
    <%= f.text_field :direccion %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<div class="row">
   <div class="col-lg-12">
      <h1 class="page-header">Editar Colegio</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>
<%= render 'form', school: @school %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<p id="notice"><%= notice %></p>


<div class="row">
   <div class="col-lg-12">
      <h1 class="page-header">Colegios</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>
              <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                <thead>
                  <tr class="text-align center">
                    <th><center>Nombre</center></th>
                    <th><center>Direccion</center></th>
                    <th colspan="3"><center>Acción</center></th>
                  </tr>
                </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.nombre %></td>
        <td><%= school.direccion %></td>
        <td><%= link_to school do%>
                            <center><i class="fa fa-eye fa-md"></i></center>
                          <%end%>
                      </td>
                      <td><%= link_to edit_school_path(school) do%>
                           <center><i class="fa fa-pencil fa-md"></i></center>
                          <%end%>
                      </td>
                      <td><%= link_to school, method: :delete, data: { confirm: 'Are you sure?' }  do%>
                            <center><i class="fa fa-trash fa-md"></i></center>
                          <%end%>
                      </td>
                    </tr>
                  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School', new_school_path %>

app/views/schools/new.html.erb
<div class="row">
   <div class="col-lg-12">
      <h1 class="page-header">Agregar Colegio</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>
<%= render 'form', school: @school %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>


<div class="row">
   <div class="col-lg-12">
      <h1 class="page-header">Colegios</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>
<p>
  <strong>Nombre:</strong> @school.nombre</p>
<p>  <%= @school.nombre %>
</p>

<p>
  <strong>Direccion:</strong> @school.direccion</p>
<p>  <%= @school.direccion %>
</p>
<p>
<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>
</p>

<div class="row">
   <div class="col-lg-12">
      <h1 class="page-header">Estudiantes</h1> 
  </div>
  <!-- /.col-lg-12 -->
</div>
<p>
  <strong>Para la tabla</strong></p>
<p>@estudiantes=Student.where(:school_id => @school.id)</p>

<p>
  <strong>Total de estudiantes:</strong> @estudiantes.count</p>
<p>  <%= @num_total %>
</p>

<p>
  <strong>Total de estudiantes masculinos:</strong>  @estudiantes.where(:genero => "M").count </p>
  <p><%= @num_total_m %></p>


<table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                <thead>
                  <tr class="text-align center">
                    <th><center>Cedula</center></th>
                    <th><center>Nombre</center></th>
                    <th><center>Apellido</center></th>
                    <th><center>Fecha Nacimiento</center></th>
                    <th><center>Genero</center></th>
                  </tr>
                </thead>
  <tbody>
    <% @estudiantes.each do |student| %>
      <tr>
        <td><%= student.cedula %></td>
        <td><%= student.nombre %></td>
        <td><%= student.apellido %></td>
        <td><%= student.fecha_nac %></td>
        <td><%= student.genero %></td>
        </tr> 
        <%end%>       
  </tbody>
</table>

<div class="row">
   <div class="col-lg-12">
      <h1 class="page-header">Materias </h1>
  </div>
  <!-- /.col-lg-12 -->
</div>
<p>
  <strong>Para la tabla</strong></p>
<p> @id_materias=StudentSubject.select(:subject_id).joins(:student).where(
      :students => {:school_id => @school.id}) </p>
   <p> @materias_impartidas=Subject.where(:id => @id_materias)</p>

<p>
  <strong>Para el promedio</strong> StudentSubject.where(:subject_id => materia.id).average(:nota)</p>
<p>  <%= @num_total %>
</p>

<table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                <thead>
                  <tr class="text-align center">
                    <th><center>Nombre</center></th>
                    <th><center>Promedio de notas</center></th>
                  </tr>
                </thead>
  <tbody>
    <% @materias_impartidas.each do |materia| %>
      <tr>
        <td><%= materia.nombre %></td>
        <td><%= StudentSubject.where(:subject_id => materia.id).average(:nota) %></td>
        </tr> 
        <%end%>       
  </tbody>
</table>