config/routes.rb
Rails.application.routes.draw do
  resources :student_subjects
  resources :subjects
  resources :students
  resources :schools
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExpoActiveRecord</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"><strong>ACTIVE RECORD</strong></a>
            </div>
     
        </nav>
                <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li> 
                        <%=link_to schools_path do%>                       
                                <p style="font-size:18px"><i class="fa fa-institution"></i> Colegio</p>
                                <%end%>
                        </li>
                        <li>
                        <%=link_to students_path do%>    
                                <p style="font-size:18px"><i class="fa fa-address-card-o"></i> Estudiantes</p>
                                <%end%>
                        </li>                        
                        <li>
                        <%=link_to subjects_path do%>    
                                <p style="font-size:18px"><i class="fa fa-flask"></i> Materias</p>
                                <%end%>
                        </li>
                        <li>
                        <%=link_to student_subjects_path do%>    
                                <p style="font-size:18px"><i class="fa fa-mortar-board"></i> Inscripcion</p>
                                <%end%>
                        </li>

                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
    <div id="page-wrapper">
      <%= yield %>
    </div>

    <footer>
        <div class="container text-center">
            <p>Exposicion de Active Record 2017</p>
        </div>
    </footer>

  </body>
</html>